# 5-1 : Conv Layers

### Code.5-1-1 : Shapes of Conv Layers

In [1]:
import tensorflow as tf

from  tensorflow.keras.layers import Conv2D # Conv Layers 

N, n_H, n_W, n_C = 1, 28, 28, 1 # Picture num , (pixel, pixel, channel)
n_filter = 1 # no of filter : 1
k_size = 3   # filter_size(kernel size) : 3 => equal with window size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape) # 28 - 3 + 1 = 26

(1, 28, 28, 1)
(3, 3, 1, 1)
(1,)
(1, 26, 26, 1)


In [2]:
# input channel 수를 다르게 설정할 경우

import tensorflow as tf

from  tensorflow.keras.layers import Conv2D # Conv Layers 

N, n_H, n_W, n_C = 1, 28, 28, 5 # Color Channel
n_filter = 1 # no of filter : 1
k_size = 3   # filter_size(kernel size) : 3 => equal with window size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)    # (3, 3, 5, 1) ; 5 => input channel 과 동일하다. => input x channel => scalar (단일 값) 
print(B.shape)
print(y.shape) # 28 - 3 + 1 = 26

(1, 28, 28, 5)
(3, 3, 5, 1)
(1,)
(1, 26, 26, 1)


In [3]:
# 커널 개수를 다르게 설정할 경우

import tensorflow as tf
from  tensorflow.keras.layers import Conv2D # Conv Layers 


N, n_H, n_W, n_C = 1, 28, 28, 5 # Color Channel
n_filter = 10 # no of filter : 10
k_size = 3   # filter_size(kernel size) : 3 => equal with window size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape) # (3, 3, 5, 10) : (3, 3, 5) shape 의 커널이 10개 만들어진다 => 총 10장의 이미지를 만든다
print(B.shape) # 각 커널마다 bias 존재 => 커널 수 : 10 => no of bias : 10
print(y.shape) # (1, 26, 26, 10) : 10 은 커널 개수와 동일 => (26, 26, 10) shape 의 이미지 하나 생성

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


### Code.5-1-2: Correlation Calculation

In [4]:
import numpy as np
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1 
k_size = 3   

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)
print("Y(Tensorflow): ", y.numpy().shape)
print("Squeeze Y(Tensorflow): ", y.numpy().squeeze().shape) # 1 drop
print("Y(Tensorflow): \n", y.numpy().squeeze()) # 1 drop => 5 - 3 + 1 = 3
W, B = conv.get_weights()

###########################################################################
print("\n", images.shape)
print(W.shape)
print(B.shape)

images = images.numpy().squeeze()
W = W.squeeze()

print("\n", images.shape)
print(W.shape)
print(B.shape)

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1)) # make empty space

# i, j => 초기 인덱스
for i in range(n_H - k_size + 1) : 
    for j in range(n_W - k_size + 1) : 
        window = images[i : i+k_size , j:j+k_size] # window size 만큼 뽑아온다.
        y_man[i, j] = np.sum(window * W) + B       # element wise product + bias 

print("Y(Manual): \n",y_man)

Y(Tensorflow):  (1, 3, 3, 1)
Squeeze Y(Tensorflow):  (3, 3)
Y(Tensorflow): 
 [[-0.98945683 -0.07756502 -0.62531245]
 [-0.78489333 -0.656262   -0.18350028]
 [-0.618248   -0.57025295 -1.3078375 ]]

 (1, 5, 5, 1)
(3, 3, 1, 1)
(1,)

 (5, 5)
(3, 3)
(1,)
Y(Manual): 
 [[-0.98945683 -0.07756504 -0.62531245]
 [-0.78489333 -0.65626198 -0.18350028]
 [-0.61824799 -0.57025295 -1.30783772]]


### Code.5-1-3: Correlation with n-channel

In [5]:
import numpy as np 
import tensorflow as tf 

from tensorflow.keras.layers import Conv2D 

N, n_H, n_W, n_C = 1, 5, 5, 3 
n_filter = 1
k_size = 3 # kernel size

images = tf.random.uniform(shape = ((N, n_H, n_W, n_C)), 
                           minval = 0 , maxval = 1)

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print("Y(Tensorflow): \n", y.numpy().squeeze())
W, B = conv.get_weights()

#### 
images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1)) # make empty space

# i, j => 초기 인덱스
for i in range(n_H - k_size + 1) : 
    for j in range(n_W - k_size + 1) : 
        window = images[i : i+k_size , j:j+k_size, :] # window size 만큼 뽑아온다.
        y_man[i, j] = np.sum(window * W) + B       # element wise product + bias 

print("Y(Manual): \n",y_man)

Y(Tensorflow): 
 [[-0.0796328  -0.11534123 -0.03120061]
 [-0.17948559 -0.4942952   0.1840231 ]
 [-0.43996572 -0.08100888 -0.43328995]]
(5, 5, 3)
(3, 3, 3)
Y(Manual): 
 [[-0.07963274 -0.1153412  -0.03120055]
 [-0.17948553 -0.49429515  0.18402317]
 [-0.43996572 -0.08100888 -0.43328995]]


#5-2 : Conv Layer with Filters

### Code.5-2-1: Shapes with Filters

In [6]:
# 딥러닝에서 중요한 것 먼저 shape 을 따져 보는 것

import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3 # 사진 개수 , Height, Weight, Channel
n_filter = 5 # (no of filter) # conv layer 를 지날때 channel 의 수를 결정
f_size = 3   # kernel_size = filter_size = window_size (3 x 3)

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = (N, n_H, n_W, n_C))
conv = Conv2D(filters = n_filter, kernel_size = f_size)

Y = conv(images)

W, B = conv.get_weights() 

print("Input Image : {}".format(images.shape))
print("W/B : {} / {}".format(W.shape, B.shape))
print("Output Image : {}".format(Y.shape))

Input Image : (1, 28, 28, 3)
W/B : (3, 3, 3, 5) / (5,)
Output Image : (1, 26, 26, 5)


### Code.5-2-2: Computations with Filters 


In [7]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3 # 사진 개수 , Height, Weight, Channel
n_filter = 3
k_size = 4 # kernel_size = filter_size


images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = (N, n_H, n_W, n_C))

# Forward Porpagation(Temsprflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
Y = conv(images)
print(Y.shape)
print(Y.numpy().squeeze().shape)

# Channel shape 을 가장 앞 차원으로 바꿔주는 작업 => channel 별 행렬이 반환
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print("Y(Transpose Shape) :", Y.shape)
print("Y(Transpose): \n" , Y)

# Forward Propagation(Manual)
W, B = conv.get_weights() # layer 에서 W, B 받아온다. 
images = images.numpy().squeeze()

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter)) # input 의 Height, Weight - kernel size
for c in range(n_filter) : 
    c_W = W[:, :, :, c]
    c_b = B[c]

    for h in range(n_H - k_size + 1) :
        for j in range(n_W - k_size + 1) : 
            window = images[h:h+k_size, j:j+k_size, :]
            conv = np.sum(window*c_W) + c_b

            y_man[h, j, c] = conv 


print(y_man.shape) 


(1, 2, 2, 3)
(2, 2, 3)
Y(Transpose Shape) : (3, 2, 2)
Y(Transpose): 
 [[[ 0.3183488  -0.20421043]
  [ 0.69331396  0.01224877]]

 [[-1.0782478  -0.653434  ]
  [-1.076916   -0.5578353 ]]

 [[-0.1540227  -0.47093463]
  [ 0.14205301 -0.8741344 ]]]
(2, 2, 3)


In [8]:
import numpy as np

images = np.random.randint(low = 0, high = 10, size = (2, 3, 4))
print(images)
print("\n", images.shape)

for c in range(4) :
    print(images[:, :, c])

# transpose 
images = np.transpose(images, (2, 0, 1) ) # 전치
print("\n", images.shape)

for c in range(4) : 
    print(images[c, :, :])

[[[7 2 4 5]
  [8 4 2 2]
  [8 8 0 5]]

 [[4 8 2 0]
  [6 0 1 8]
  [4 6 7 0]]]

 (2, 3, 4)
[[7 8 8]
 [4 6 4]]
[[2 4 8]
 [8 0 6]]
[[4 2 0]
 [2 1 7]]
[[5 2 5]
 [0 8 0]]

 (4, 2, 3)
[[7 8 8]
 [4 6 4]]
[[2 4 8]
 [8 0 6]]
[[4 2 0]
 [2 1 7]]
[[5 2 5]
 [0 8 0]]


# 5-3: Conv Layers with Activation Functions

### Code.5-3-1:Conv Layers with Activation Functions

In [9]:
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D
import numpy as np

N, n_H, n_W, n_C = 1, 28, 28, 3 # 사진 개수 , Height, Weight, Channel
n_filter = 5
f_size = 3 # kernel_size = filter_size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = (N, n_H, n_W, n_C))

conv = Conv2D(filters = n_filter, kernel_size = f_size, activation = "sigmoid")
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze() , (2,0,1))
print("Y(TensorFlow : \n ", Y)

W, B = conv.get_weights() 

# Forward Propagation (Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape = (n_H - f_size + 1,
                          n_W - f_size + 1,
                          n_filter))
for c in range(n_filter) : 
    c_W = W[:, :, :, c]
    c_b = B[c]

    for h in range(n_H - f_size + 1) : 
        for j in range(n_W - f_size + 1) : 
            window = images[h:h+f_size , j:j+f_size, :]
            conv = np.sum(window * c_W + c_b)
            conv = 1 / (1 + np.exp(-conv))

            Y_man[h, j, c] = conv

print("Y(Manual): \n" ,np.transpose(Y_man , (2, 0, 1)))

Y(TensorFlow : 
  [[[0.37066415 0.473337   0.3753578  ... 0.5248787  0.36309373 0.37122792]
  [0.42448115 0.4093281  0.3573844  ... 0.44259983 0.40353408 0.40412632]
  [0.41787708 0.37414792 0.35980195 ... 0.3264721  0.4266889  0.40697122]
  ...
  [0.32606107 0.40002236 0.41238946 ... 0.44580445 0.42044342 0.35893655]
  [0.3458489  0.3309682  0.3150129  ... 0.43595037 0.37696674 0.4163901 ]
  [0.41449767 0.4313102  0.45719057 ... 0.38475907 0.3754002  0.42772013]]

 [[0.49019745 0.73031414 0.623076   ... 0.6530406  0.62536895 0.6880981 ]
  [0.6962631  0.58406055 0.7582544  ... 0.5827974  0.64832103 0.70913094]
  [0.72617    0.6357459  0.6450433  ... 0.6102759  0.585184   0.64348805]
  ...
  [0.6821717  0.7183846  0.6026099  ... 0.71782213 0.49892747 0.7185059 ]
  [0.66275895 0.7366636  0.5819283  ... 0.6108961  0.6480867  0.5169532 ]
  [0.7028382  0.61896735 0.7451847  ... 0.6817342  0.5636437  0.62481034]]

 [[0.45760697 0.6687925  0.6732292  ... 0.5449854  0.6587895  0.6907211 ]
  [0

# 5-4:Models with Conv Layers

### Code. 5-4-1 : Models with Sequential Method

In [10]:
import tensorflow as tf 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

model = Sequential()
model.add(Conv2D(filters = n_neurons[0], kernel_size = 3, activation = "relu"))
model.add(Conv2D(filters = n_neurons[1], kernel_size = 3, activation = "relu"))
model.add(Conv2D(filters = n_neurons[2], kernel_size = 3, activation = "relu"))

x = tf.random.normal(shape = (32, 28, 28, 3)) 
predictions = model(x) 

print("Input : {}".format(x.shape))
print("Output : {}".format(predictions.shape))

for layer in model.layers : 
    W, B = layer.get_weights() 
    print(W.shape, B.shape)

print("=======")
trainable_variables = model.trainable_variables
for train_var in trainable_variables : 
    print(train_var.shape)


Input : (32, 28, 28, 3)
Output : (32, 22, 22, 30)
(3, 3, 3, 10) (10,)
(3, 3, 10, 20) (20,)
(3, 3, 20, 30) (30,)
(3, 3, 3, 10)
(10,)
(3, 3, 10, 20)
(20,)
(3, 3, 20, 30)
(30,)


### Code.5-4-2: Models with Model Sub-classing

In [11]:
import tensorflow as tf 

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

class TestModel(Model) : 
    def __init__(self) : 
        super(TestModel, self).__init__()
        global n_neurons

        self.conv_layers = [] 
        for n_neuron in n_neurons : 
            self.conv_layers.append(Conv2D(filters = n_neuron, kernel_size = 3, activation = "relu"))

    def call(self, x) : 
        print("Input: ", x.shape)
        
        print("\n===== Conv Layers =====\n")
        for conv_layer in self.conv_layers : 
            x = conv_layer(x)
            W, B = conv_layer.get_weights()
            print("W/B : {}/{}".format(W.shape, B.shape)) 
            print("X : {}\n".format(x.shape))
        return x

model = TestModel()
x = tf.random.normal(shape = (32, 28, 28, 3)) 
predictions = model(x)

Input:  (32, 28, 28, 3)

===== Conv Layers =====

W/B : (3, 3, 3, 10)/(10,)
X : (32, 26, 26, 10)

W/B : (3, 3, 10, 20)/(20,)
X : (32, 24, 24, 20)

W/B : (3, 3, 20, 30)/(30,)
X : (32, 22, 22, 30)



# 6-1:Max/Avg Pooling

### Code,6-1-1:Max Pooling

In [12]:
import numpy as np 
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

# L : Length , f : pooling size , s : strides
L, f, s = 10, 2, 1

x = tf.random.normal(shape = (1, L, 1)) # 길이가 10 인 1차원 벡터
# max pooling
pool_max = MaxPooling1D(pool_size = f, strides = s)
pooled_max = pool_max(x)

print("x : {}\n{}".format(x.shape, x.numpy().flatten()))
# 10 - 2 + 1 
print("\npooled max(Tensorflow) : {}\n{}".format(pooled_max.shape,
                                               pooled_max.numpy().flatten()))

x = x.numpy().flatten()

# pooling layer 구현
pooled_max_man = np.zeros((L- f + 1, )) 

for i in range(L - f + 1) : 
    window = x[i:i+f]
    pooled_max_man[i] = np.max(window)

print("\npooled max(Manual) : {}\n{}".format(pooled_max_man.shape,
                                               pooled_max_man))

x : (1, 10, 1)
[-1.4173095   1.7323217   0.09157097  0.02696924  0.7772016   0.28438842
 -0.59988964 -1.0800021  -0.08656622  0.34426874]

pooled max(Tensorflow) : (1, 9, 1)
[ 1.7323217   1.7323217   0.09157097  0.7772016   0.7772016   0.28438842
 -0.59988964 -0.08656622  0.34426874]

pooled max(Manual) : (9,)
[ 1.73232174  1.73232174  0.09157097  0.77720159  0.77720159  0.28438842
 -0.59988964 -0.08656622  0.34426874]


### Code.6-1-2: Average Pooling

In [13]:
import numpy as np 
import tensorflow as tf 

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1 

# input
x = tf.random.normal(shape = (1, L, 1))
pooled_average = AveragePooling1D(pool_size = f, strides = s)
pooled_average = pooled_average(x)

print("x : {}\n{}".format(x.shape, x.numpy().flatten()))
print("\npooled average(Tensorflow) : {}\n{}".format(pooled_average.shape,
                                               pooled_average.numpy().flatten()))

# AveragePooling 1D 구현
x = x.numpy().flatten() # 벡터
pooled_average_man = np.zeros(shape = (L - f + 1, ))

for i in range(L - f + 1) : 
    window = x[i:i+f]
    pooled_average_man[i] = np.mean(window)

print("\npooled average(Manual) : {}\n{}".format(pooled_average_man.shape,
                                               pooled_average_man))

x : (1, 10, 1)
[ 0.36425978  0.4471421  -0.35750642  0.01626199 -0.01317488 -0.11498342
  1.1575291  -0.02603191 -0.8295343  -0.48877567]

pooled average(Tensorflow) : (1, 9, 1)
[ 0.40570092  0.04481784 -0.17062221  0.00154356 -0.06407915  0.52127284
  0.5657486  -0.4277831  -0.659155  ]

pooled average(Manual) : (9,)
[ 0.40570092  0.04481784 -0.17062221  0.00154356 -0.06407915  0.52127284
  0.56574857 -0.4277831  -0.65915501]


# 6-2:2D Max/Avg Pooling

### Code.6-2-1:2D Max Pooling

In [14]:
import numpy as np 
import tensorflow as tf 

from tensorflow.keras.layers import MaxPooling2D

# N : no of Data, n_H : Height, n_W : Width, n_C : no of Channel ((ex) RGB)
N , n_H, n_W, n_C = 1, 5, 5, 1 
f , s = 2, 1

x = tf.random.normal(shape = (N , n_H, n_W, n_C))
# 2D Pooling Layer
pool_max = MaxPooling2D(pool_size = f, strides = s) 
pooled_max = pool_max(x)

# shape :  (n_H - f + 1 , n_W - f + 1)
print("x : {}\n{}".format(x.shape, x.numpy().squeeze()))
print("\npooled MAX(Tensorflow) : {}\n{}".format(pooled_max.shape,
                                               pooled_max.numpy().squeeze()))

# Manually 구현
x = x.numpy().squeeze() 
pooled_max_man = np.zeros(shape = (n_H - f + 1,
                                   n_W - f + 1))
for i in range(n_H - f + 1) :
    for j in range(n_W - f + 1) : 
        window = x[i:i+f , j:j+f]
        pooled_max_man[i, j] = np.max(window)

print("\npooled max(Manual) : {}\n{}".format(pooled_max_man.shape,
                                             pooled_max_man))

x : (1, 5, 5, 1)
[[ 0.29656184  0.4473907  -1.726714    0.09629627 -0.6044678 ]
 [ 0.4457347  -0.6949654   0.26280564  0.6605116  -1.6189727 ]
 [-1.4640644  -0.7174623  -0.27936146  1.4802158   0.3624685 ]
 [-0.8240539  -0.6005646   1.307583   -0.44545138  1.23725   ]
 [-0.4399014   1.5525166   1.0765431  -1.1320386  -1.6662828 ]]

pooled MAX(Tensorflow) : (1, 4, 4, 1)
[[ 0.4473907   0.4473907   0.6605116   0.6605116 ]
 [ 0.4457347   0.26280564  1.4802158   1.4802158 ]
 [-0.6005646   1.307583    1.4802158   1.4802158 ]
 [ 1.5525166   1.5525166   1.307583    1.23725   ]]

pooled max(Manual) : (4, 4)
[[ 0.44739071  0.44739071  0.66051161  0.66051161]
 [ 0.44573471  0.26280564  1.48021579  1.48021579]
 [-0.6005646   1.30758297  1.48021579  1.48021579]
 [ 1.55251658  1.55251658  1.30758297  1.23724997]]


### Code.6-2-2:2D Average Pooling

In [15]:
import numpy as np 
import tensorflow as tf 

from tensorflow.keras.layers import AveragePooling2D

# N : no of Data, n_H : Height, n_W : Width, n_C : no of Channel ((ex) RGB)
N , n_H, n_W, n_C = 1, 5, 5, 1 
f , s = 2, 1

x = tf.random.normal(shape = (N , n_H, n_W, n_C))
# 2D Pooling Layer
pool_avg = AveragePooling2D(pool_size = f, strides = s) 
pooled_avg = pool_avg(x)

# shape :  (n_H - f + 1 , n_W - f + 1)
print("x : {}\n{}".format(x.shape, x.numpy().squeeze()))
print("\npooled Avg(Tensorflow) : {}\n{}".format(pooled_avg.shape,
                                               pooled_avg.numpy().squeeze()))

# Manually 구현
x = x.numpy().squeeze() 
pooled_avg_man = np.zeros(shape = (n_H - f + 1,
                                   n_W - f + 1))
for i in range(n_H - f + 1) :
    for j in range(n_W - f + 1) : 
        window = x[i:i+f , j:j+f]
        pooled_avg_man[i, j] = np.mean(window)

print("\npooled Avg(Manual) : {}\n{}".format(pooled_avg_man.shape,
                                             pooled_avg_man))

x : (1, 5, 5, 1)
[[ 0.35724115  0.9185706  -0.65675044  0.3482984  -0.91917926]
 [-0.4062435   0.18567826 -0.6008859  -1.3655939  -0.5334185 ]
 [-0.95705664  0.0897655   1.9501624   0.8567881  -1.6463137 ]
 [-0.5681844   0.9871396  -0.52332616 -0.37232265  0.40719908]
 [-1.4476299   0.16841047 -0.4759818   0.14307138  0.30707088]]

pooled Avg(Tensorflow) : (1, 4, 4, 1)
[[ 0.26381162 -0.03834689 -0.568733   -0.6174733 ]
 [-0.27196407  0.40618005  0.21011768 -0.67213446]
 [-0.112084    0.6259354   0.47782543 -0.18866228]
 [-0.21506606  0.03906053 -0.3071398   0.12125468]]

pooled Avg(Manual) : (4, 4)
[[ 0.26381162 -0.03834689 -0.56873298 -0.6174733 ]
 [-0.27196407  0.40618005  0.21011768 -0.67213446]
 [-0.112084    0.62593538  0.47782543 -0.18866228]
 [-0.21506606  0.03906053 -0.30713981  0.12125468]]


# 6-3: 3D Max/Avg Pooling

### Code.6-3-1:3D Max Pooling

In [21]:
# Multi Channel
import math
import numpy as np 
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
# print("x : {}\n{}".format(np.transpose(x.numpy().squeeze(), (2, 0, 1)).shape, 
#                          np.transpose(x.numpy().squeeze(), (2, 0, 1)))) # (5, 5) 3 장

pool_max = MaxPooling2D(pool_size = f, strides = s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print("\nPooled_max(Tensorflow):{}\n{}".format(pooled_max.shape,
                                           pooled_max_t))

#### 
# (n_H -f) / s + 1 
# math.floor(45.9338) = 45

x = x.numpy().squeeze()
n_H_ = math.floor((n_H -f)/s + 1) # integer 이어야 하기 때문
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C))

for c in range(n_C) : 
    c_image = x[:, :, c]

    h_ = 0 
    for h in range(0, n_H - f + 1, s) : 
        w_ = 0
        for w in range(0, n_W - f + 1, s) : 
            window = c_image[h:h+f , w:w+f]
            pooled_max_man[h_ , w_ , c] = np.max(window)
            w_ += 1 
        h_ += 1

# 채널별로 max pooling 이 이루어진다. 

pooled_max_t = np.transpose(pooled_max_man, (2, 0, 1))
print("pooled_max(Manual) :{}\n{}".format(pooled_max_man.shape,
                                          pooled_max_t))


Pooled_max(Tensorflow):(1, 2, 2, 3)
[[[0.9195631 1.2863643]
  [1.7281797 1.9093393]]

 [[2.2474697 0.2298464]
  [1.6955317 2.0475528]]

 [[1.9092835 1.6530879]
  [2.7489176 1.257806 ]]]
pooled_max(Manual) :(2, 2, 3)
[[[0.91956311 1.28636432]
  [1.72817969 1.90933931]]

 [[2.24746966 0.2298464 ]
  [1.69553173 2.04755282]]

 [[1.90928352 1.65308785]
  [2.74891758 1.25780594]]]


# 6-4: Padding

### Code.6-4-1:ZeroPadding2D Layer

In [36]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape = (1, 28, 28, 3))
print(images.shape)
# print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

zero_padding = ZeroPadding2D(padding = 2) 
y = zero_padding(images) # tensor
print(y.shape)
# print(np.transpose(y.numpy().squeeze(), (2,0,1)))

(1, 28, 28, 3)
(1, 32, 32, 3)


### Code.6-4-2:Zero Padding with Conv2D Layers

In [38]:
import tensorflow as tf 

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1, 28, 28, 3))
# padding = "same" => kernel size 에 맞춰 자동으로 수행
conv = Conv2D(filters = 1, kernel_size = 3, padding = "same") # valid => padding x
y = conv(images)
print(y.shape)

(1, 28, 28, 1)


# 6-5:Strides

### Code.6-5-1:Strides in Conv2D Layers

In [39]:
import tensorflow as tf 

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1, 28, 28, 3))
conv = Conv2D(filters = 1, kernel_size = 3, padding = "valid", strides = 2)

y = conv(images)
print(images.shape)
print(y.shape) # (1, 13, 13, 1)



(1, 28, 28, 3)
(1, 13, 13, 1)


### Code.6-5-2: Strides in Pooling Layers

In [40]:
import tensorflow as tf 

from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape = (1, 28, 28, 3))
pool = MaxPooling2D(pool_size = 3, strides = 2)

y = pool(images)
print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)


# 7-1: Shapes in CNNs  

### Code.7-1-1: Shapes in the Feature Extractors

In [54]:
import tensorflow as tf 

from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten

N, n_H, n_W, n_C = 32, 28, 28, 3
n_conv_filter = 5
k_size = 3
pool_size , pool_strides = 2 , 2
batch_size = 32 

x = tf.random.normal(shape = (N, n_H, n_W, n_C))

## 합성곱 수행 
conv1 = Conv2D(filters = n_conv_filter , # filter size
              kernel_size = k_size,      # kernel size
              padding = "same",          # padding = "same" : input and output of (n_H, n_W) shape becomes same
              activation = "relu")
## 풀링
conv1_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides) # ((n_H - f) / 2) + 1

## 
conv2 = Conv2D(filters = n_conv_filter ,
              kernel_size = k_size, 
              padding = "same",     # padding
              activation = "relu")
conv2_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)

### flatten layer
flatten = Flatten()

print("Input : {}\n".format(x.shape))
x = conv1(x)
W, B = conv1.get_weights()
print("W/B : {}/{}".format(W.shape, B.shape))
print("After conv1: {}\n".format(x.shape))
x = conv1_pool(x)
print("After conv1_pool: {}\n".format(x.shape))

x = conv2(x)
W, B = conv2.get_weights()
print("W/B : {}/{}".format(W.shape, B.shape))
print("After conv2: {}\n".format(x.shape))
x = conv2_pool(x)
print("After conv2_pool: {}\n".format(x.shape))
x = flatten(x)
print("After flatten: {}\n".format(x.shape)) # 7x7x5 = 245

Input : (32, 28, 28, 3)

W/B : (3, 3, 3, 5)/(5,)
After conv1: (32, 28, 28, 5)

After conv1_pool: (32, 14, 14, 5)

W/B : (3, 3, 5, 5)/(5,)
After conv2: (32, 14, 14, 5)

After conv2_pool: (32, 7, 7, 5)

After flatten: (32, 245)



### Code.7-1-2: Shapes in the Classifier

In [55]:
from tensorflow.keras.layers import Dense

n_neurons = [50, 25, 10]

dense1 = Dense(units = n_neurons[0], activation = "relu")
dense2 = Dense(units = n_neurons[1], activation = "relu")
dense3 = Dense(units = n_neurons[2], activation = "softmax")

print("Input feature : {}\n".format(x.shape))
x = dense1(x)
W, B = dense1.get_weights()
print("W/B : {}/{}".format(W.shape, B.shape))
print("After dense1: {}\n".format(x.shape))
x = dense2(x)
W, B = dense2.get_weights()
print("W/B : {}/{}".format(W.shape, B.shape))
print("After dense2: {}\n".format(x.shape))
x = dense3(x)
W, B = dense3.get_weights()
print("W/B : {}/{}".format(W.shape, B.shape))
print("After dense3: {}\n".format(x.shape))

Input feature : (32, 245)

W/B : (245, 50)/(50,)
After dense1: (32, 50)

W/B : (50, 25)/(25,)
After dense2: (32, 25)

W/B : (25, 10)/(10,)
After dense3: (32, 10)



### Shapes in the Loss Functions