# 5-1 : Conv Layers

### Code.5-1-1 : Shapes of Conv Layers

In [ ]:
import tensorflow as tf

from  tensorflow.keras.layers import Conv2D # Conv Layers 

N, n_H, n_W, n_C = 1, 28, 28, 1 # Picture num , (pixel, pixel, channel)
n_filter = 1 # no of filter : 1
k_size = 3   # filter_size(kernel size) : 3 => equal with window size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape) # 28 - 3 + 1 = 26

(1, 28, 28, 1)
(3, 3, 1, 1)
(1,)
(1, 26, 26, 1)


In [ ]:
# input channel 수를 다르게 설정할 경우

import tensorflow as tf

from  tensorflow.keras.layers import Conv2D # Conv Layers 

N, n_H, n_W, n_C = 1, 28, 28, 5 # Color Channel
n_filter = 1 # no of filter : 1
k_size = 3   # filter_size(kernel size) : 3 => equal with window size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)    # (3, 3, 5, 1) ; 5 => input channel 과 동일하다. => input x channel => scalar (단일 값) 
print(B.shape)
print(y.shape) # 28 - 3 + 1 = 26

(1, 28, 28, 5)
(3, 3, 5, 1)
(1,)
(1, 26, 26, 1)


In [ ]:
# 커널 개수를 다르게 설정할 경우

import tensorflow as tf
from  tensorflow.keras.layers import Conv2D # Conv Layers 


N, n_H, n_W, n_C = 1, 28, 28, 5 # Color Channel
n_filter = 10 # no of filter : 10
k_size = 3   # filter_size(kernel size) : 3 => equal with window size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape) # (3, 3, 5, 10) : (3, 3, 5) shape 의 커널이 10개 만들어진다 => 총 10장의 이미지를 만든다
print(B.shape) # 각 커널마다 bias 존재 => 커널 수 : 10 => no of bias : 10
print(y.shape) # (1, 26, 26, 10) : 10 은 커널 개수와 동일 => (26, 26, 10) shape 의 이미지 하나 생성

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


### Code.5-1-2: Correlation Calculation

In [ ]:
import numpy as np
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1 
k_size = 3   

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

# conv layer
conv = Conv2D(filters = n_filter , kernel_size = k_size)

y = conv(images)
print("Y(Tensorflow): ", y.numpy().shape)
print("Squeeze Y(Tensorflow): ", y.numpy().squeeze().shape) # 1 drop
print("Y(Tensorflow): \n", y.numpy().squeeze()) # 1 drop => 5 - 3 + 1 = 3
W, B = conv.get_weights()

###########################################################################
print("\n", images.shape)
print(W.shape)
print(B.shape)

images = images.numpy().squeeze()
W = W.squeeze()

print("\n", images.shape)
print(W.shape)
print(B.shape)

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1)) # make empty space

# i, j => 초기 인덱스
for i in range(n_H - k_size + 1) : 
    for j in range(n_W - k_size + 1) : 
        window = images[i : i+k_size , j:j+k_size] # window size 만큼 뽑아온다.
        y_man[i, j] = np.sum(window * W) + B       # element wise product + bias 

print("Y(Manual): \n",y_man)

Y(Tensorflow):  (1, 3, 3, 1)
Squeeze Y(Tensorflow):  (3, 3)
Y(Tensorflow): 
 [[1.3655933  0.9273002  0.798546  ]
 [0.86220795 0.7843926  0.56220806]
 [0.56239855 0.8855889  0.57006997]]

 (1, 5, 5, 1)
(3, 3, 1, 1)
(1,)

 (5, 5)
(3, 3)
(1,)
Y(Manual): 
 [[1.36559331 0.92730021 0.79854602]
 [0.86220801 0.7843926  0.56220806]
 [0.56239855 0.88558888 0.57006997]]


### Code.5-1-3: Correlation with n-channel

In [ ]:
import numpy as np 
import tensorflow as tf 

from tensorflow.keras.layers import Conv2D 

N, n_H, n_W, n_C = 1, 5, 5, 3 
n_filter = 1
k_size = 3 # kernel size

images = tf.random.uniform(shape = ((N, n_H, n_W, n_C)), 
                           minval = 0 , maxval = 1)

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print("Y(Tensorflow): \n", y.numpy().squeeze())
W, B = conv.get_weights()

#### 
images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1)) # make empty space

# i, j => 초기 인덱스
for i in range(n_H - k_size + 1) : 
    for j in range(n_W - k_size + 1) : 
        window = images[i : i+k_size , j:j+k_size, :] # window size 만큼 뽑아온다.
        y_man[i, j] = np.sum(window * W) + B       # element wise product + bias 

print("Y(Manual): \n",y_man)

Y(Tensorflow): 
 [[0.08031283 0.7201033  1.0631112 ]
 [1.3258499  0.67909056 0.3208626 ]
 [0.6498039  0.94820327 0.34377015]]
(5, 5, 3)
(3, 3, 3)
Y(Manual): 
 [[0.08031285 0.72010332 1.06311119]
 [1.32584977 0.67909062 0.32086259]
 [0.64980394 0.94820327 0.34377009]]


#5-2 : Conv Layer with Filters

### Code.5-2-1: Shapes with Filters

In [4]:
# 딥러닝에서 중요한 것 먼저 shape 을 따져 보는 것

import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3 # 사진 개수 , Height, Weight, Channel
n_filter = 5
f_size = 3 # kernel_size = filter_size

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = (N, n_H, n_W, n_C))
conv = Conv2D(filters = n_filter, kernel_size = f_size)

Y = conv(images)

W, B = conv.get_weights() 

print("Input Image : {}".format(images.shape))
print("W/B : {} / {}".format(W.shape, B.shape))
print("Output Image : {}".format(Y.shape))

Input Image : (1, 28, 28, 3)
W/B : (3, 3, 3, 5) / (5,)
Output Image : (1, 26, 26, 5)


### Code.5-2-2: Computations with Filters 


In [39]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3 # 사진 개수 , Height, Weight, Channel
n_filter = 3
k_size = 4 # kernel_size = filter_size


images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = (N, n_H, n_W, n_C))

# Forward Porpagation(Temsprflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
Y = conv(images)
print(Y.shape)
print(Y.numpy().squeeze().shape)

# Channel shape 을 가장 앞 차원으로 바꿔주는 작업 => channel 별 행렬이 반환
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print("Y(Transpose Shape) :", Y.shape)
print("Y(Transpose): \n" , Y)

# Forward Propagation(Manual)
W, B = conv.get_weights() # layer 에서 W, B 받아온다. 
images = images.numpy().squeeze()

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter)) # input 의 Height, Weight - kernel size
for c in range(n_filter) : 
    c_W = W[:, :, :, c]
    c_b = B[c]

    for h in range(n_H - k_size + 1) :
        for j in range(n_W - k_size + 1) : 
            window = images[h:h+k_size, j:j+k_size, :]
            conv = np.sum(window*c_W) + c_b

            y_man[h, j, c] = conv 


print(y_man.shape) 


(1, 2, 2, 3)
(2, 2, 3)
Y(Transpose Shape) : (3, 2, 2)
Y(Transpose): 
 [[[ 0.63677734  0.9919338 ]
  [ 0.6209436   0.8231532 ]]

 [[-0.61753106 -0.6974499 ]
  [-0.72296417 -0.92476934]]

 [[-0.09741174 -0.20192444]
  [-0.11202966 -0.03926793]]]
(2, 2, 3)


In [25]:
import numpy as np

images = np.random.randint(low = 0, high = 10, size = (2, 3, 4))
print(images)
print("\n", images.shape)

for c in range(4) :
    print(images[:, :, c])

# transpose 
images = np.transpose(images, (2, 0, 1) ) # 전치
print("\n", images.shape)

for c in range(4) : 
    print(images[c, :, :])

[[[6 9 0 4]
  [1 8 4 1]
  [6 3 1 0]]

 [[4 9 0 4]
  [1 5 5 1]
  [7 8 5 6]]]

 (2, 3, 4)
[[6 1 6]
 [4 1 7]]
[[9 8 3]
 [9 5 8]]
[[0 4 1]
 [0 5 5]]
[[4 1 0]
 [4 1 6]]

 (4, 2, 3)
[[6 1 6]
 [4 1 7]]
[[9 8 3]
 [9 5 8]]
[[0 4 1]
 [0 5 5]]
[[4 1 0]
 [4 1 6]]


(4, 2, 3)
[[4 3 6]
 [0 9 2]]
[[2 1 6]
 [5 1 2]]
[[4 9 3]
 [5 7 8]]
[[9 4 4]
 [4 5 3]]
