In [1]:
import tensorflow as tf
tf.__version__
import keras
keras.__version__
import gensim
gensim.__version__
import sklearn
sklearn.__version__
# nltk 임포트
import nltk
nltk.__version__

#  "드라이브 마운트" > "디렉토리 이동" > "임포트" 

### 드라이브 이동

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [17]:
!pwd

/content


In [24]:
# %cd [프로젝트 위치]
%cd /content/drive/MyDrive/project 

/content/drive/MyDrive/project


In [25]:
!ls

colab_code  dataset  module


In [18]:
import os
os.getcwd()

'/content'

In [ ]:
pip install konlpy

In [28]:
import konlpy
konlpy.__version__

'0.5.2'

# 판다스, 넘파이, 맷플롯립

In [31]:
import pandas as pd 
import numpy as np 
import matplotlib

print(pd.__version__ )
print(np.__version__ )
print(matplotlib.__version__)

1.1.5
1.19.5
3.2.2


### 넘파이의 주요 기능

1. np.array() # 리스트, 튜플, 배열로 부터 ndarray를 생성
2. np.asarray() # 기존의 array로 부터 ndarray를 생성
3. np.arange() # range와 비슷
4. np.linspace(start, end, num) # [start, end] 균일한 간격으로 num개 생성
5. np.logspace(start, end, num) # [start, end] log scale 간격으로 num개 생성

1) np.array
- Numpy 의 핵심은 ndarray , np.array() 는 리스트, 튜플, 배열로 부터 ndarray를 생성합니다. 또한 인덱스가 0부터 시작

In [32]:
a = np.array([1, 2, 3, 4, 5]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [33]:
b = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(b) #출력

[[10 20 30]
 [60 70 80]]


In [34]:
print(b.ndim) #차원 출력 # 2차원 : 행렬
print(b.shape) #크기 출력 

2
(2, 3)


2) ndarray의 초기화
- 위에서는 리스트를 가지고 ndarray를 생성했지만, ndarray를 만드는 다양한 다른 방법이 존재합니다. zeros()는 해당 배열에 모두 0을 삽입하고, ones()는 모두 1을 삽입합니다. full()은 배열에 사용자가 지정한 값을 넣는데 사용하고, eye()는 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성합니다.

In [35]:
a = np.zeros((2,3)) # 모든값이 0인 2x3 배열 생성.
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
a = np.ones((2,3))
print(a)
print(a.ndim)
print(a.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)


In [37]:
a = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성. 이 경우에는 7.
print(a)

[[7 7]
 [7 7]]


In [38]:
# 대각 행렬
a = np.eye(3) # 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성.
print(a) # 3,3 행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
a = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(a)

[[0.47249823 0.08283439]
 [0.98983659 0.1526812 ]]


### np.arange()
- np.arange()는 지정해준 범위에 대해서 배열을 생성합니다. np.arange()의 범위 지정 방법은 다음과 같습니다.

- numpy.arange(start, stop, step, dtype)
- a = np.arange(n) # 0, ..., n-1까지 범위의 지정.
- a = np.arange(i, j, k) # i부터 j-1까지 k씩 증가하는 배열.

In [40]:
a = np.arange(10)
print(a)
a = np.arange(1, 10, 2)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### reshape() 

In [41]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### Numpy 슬라이싱

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


# 판다스 프로파일링

# 머신러닝 워크플로우

### 수집(Acquisition)
- 머신러닝을 하기 위해서는 기계에 학습시켜야 할 데이터가 필요하다. 
- 자연어 데이터를 말뭉치 또는 코퍼스(corpus) 라고 부른다 
- 코퍼스의 뜻 조사나 연구 목적에 의해 특정 도메인으로부터 수집된 텍스트 집합 


### 점검 및 탐색 (Inspection and Exploration) 
- 데이터의 구조 , 노이즈, 머신 러닝 적용을 위해 데이터를 어떻게 정제해야 하는지 등을 파악해야 한다. 
- 탐색적 데이터 분석 (Exploatory Data Analysis, EDA) 단계 
- 독립 변수, 종속 변수, 변수 유형, 변수의 데이터 타입 등을 점검
- 데이터의 특징과 내재하는 구조적 관계를 알아내는 작업
- 시각화 및 간단한 통계 검정 

### 전처리 및 정제(Preprocessing and Cleansing) 
- 데이터에 대한 파악이 끝나면, 머신 러닝 워크플로우에서 가장 까다로운 작업 중 하나인 데이터 전처리 과정에 들어간다. 
- 가령 자연어 처리라고 한다면, 토큰화, 정제, 정규화, 불용어 제거 등의 단계를 포함한다. 빠르고 정확한 데이터 전처리를 하기 위해서는 사용하고 있는 툴(파이썬)에 대한 다양한 라이브러리에 대한 지식이 필요하다. 
- 정말 까다로운 전처리의 경우 전처리 과정에서 머신러닝이 사용되기도 한다

### 모델링 및 훈련 (Modeling and Training)
- 데이터 전처리가 끝나면, 머신 러닝에 대한 코드를 작성하는 단계인 모델링 단계에 들어간다. 
- 적절한 머신러닝 알고리즘들을 선택하여 모델링이 끝났다면, 전처리가 완료된 데이터를 머신 러닝 알고리즘을 통해 기계에서 학습(Training) 시킵니다. 
- 훈련 이라고도 한다. 
- 주의할점 : 대부분의 경우에서 모든 데이터를 기계에서 학습시켜서는 안된다는 점
- 데이터 중 일부는 테스트용으로 남겨두고 훈련용 데이터만 훈련에 사용해야 한다.
- 기계가 학습을 하고나서, 현재 성능이 얼마나 되는지를 측정할 수 있으며, 과적합(overfitting) 을 피할 수 있다. 
- 데이터의 양이 충분하여 더 세부적으로 나눌 수 있다면 훈련용, 검증용, 테스트용 데이터로 나눈다. 


### 평가(Evaluation) 
- 기계가 다 학습되었다면 테스트용 데이터로 성능을 평가한다. 평가 방법은 기계가 예측한 데이터가 테스트용 데이터의 실제 정답과 얼마나 가까운지를 측정한다. 

### 배포(Deployment) 
- 평가 단계에서 기계가 성공적으로 훈련이 된 것으로 판단되었다면, 완성된 모델이 배포되는 단계가 된다. 

# 텍스트 전처리 (Text Preprocessing)

# 토큰화(Tokenization)
자연어 처리에서 크롤링 등으로 얻어낸 코퍼스 데이터가 필요에 맞게 전처리되지 않은 상태라면, 해당 데이터를 사용하고자하는 용도에 맞게 토큰화(tokenization) & 정제(cleaning) & 정규화(normalization)하는 일을 하게 됩니다. 이번 챕터에서는 그 중에서도 토큰화에 대해서 배우도록 합니다.

주어진 코퍼스(corpus)에서 토큰(token)이라 불리는 단위로 나누는 작업을 토큰화(tokenization)라고 부릅니다. 토큰의 단위가 상황에 따라 다르지만, 보통 의미있는 단위로 토큰을 정의합니다.

### 단어 토큰화(Word Tokenization) 
- 토큰의 기준을 단어(word)로 하는 경우, 단어 토큰화(word tokenization)라고 합니다. 다만, 여기서 단어(word)는 단어 단위 외에도 단어구, 의미를 갖는 문자열로도 간주되기도 합니다.

### 토큰화 중 생기는 선택의 순간
- 토큰화를 하다보면 예상하지 못한 경우가 있어서, 토큰화의 기준을 생각해봐야 하는 경우가 있다. 예를 들어 영어권 언어에서 아포스트로피(') 가 들어있는 단어는 어떻게 토큰화 해야 할까? 
- 원하는 결과가 나오도록 토큰화 도구를 직접 설계할 수도 있겠지만, 기존에 공개된 도구들을 사용하였을 때의 결과가 사용자의 목적과 일치한다면 해당 도구를 사용할 수도 있을 것입니다. NLTK는 영어 코퍼스를 토큰화하기 위한 도구들을 제공합니다. 그 중 word_tokenize와 WordPunctTokenizer를 사용해서 NLTK에서는 아포스트로피를 어떻게 처리하는지 확인해보겠습니다.

 

In [47]:
import tokenize
nltk.download('punkt')
from nltk.tokenize import word_tokenize

print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


- WordPunctTokenizer는 구두점을 별도로 분류하는 특징을 갖고 있기때문에, 앞서 확인했던 word_tokenize와는 달리 Don't를 Don과 '와 t로 분리하였으며, 이와 마찬가지로 Jone's를 Jone과 '와 s로 분리한 것을 확인할 수 있습니다.

In [48]:
from nltk.tokenize import WordPunctTokenizer  
print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


- 케라스 또한 토큰화 도구로서 text_to_word_sequence를 지원합니다. 
- 케라스의 text_to_word_sequence는 기본적으로 모든 알파벳을 소문자로 바꾸면서 마침표나 컴마, 느낌표 등의 구두점을 제거합니다. 하지만 don't나 jone's와 같은 경우 아포스트로피는 보존하는 것을 볼 수 있습니다.

In [49]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


### 토큰화에서 고려해야 할 사항
- 토큰화 작업은 단순히 코퍼스에서 구두점을 제외하고 공백 기준으로 잘라내는 작업이라고 할 수 없다. 
- 이러한 일은 보다 섬세한 알고리즘이 필요하다. 
    - 1) 구두점이나 특수 문자를 단순 제외해서는 안된다. 
    - 예를 들어 ) 마침표 (.) 와 같은 경우는 문장의 경계를 알 수 있는데 도움이 되므로 단어를 뽑아낼 때, 마침표를 제외하지 않을 수 있다. 
    - 또 다른 예로는 단어 자체에 구두점이 포함되어 있을 수 있다. m.p.h 나 PH.D 와 같이 
    - 2) 줄임말과 단어 내에 띄어쓰기가 있는 경우
    - what're , we're , New York rock'n'roll 

### 표준토큰화 예제
- 표준으로 쓰이고 있는 토큰화 방법 중 하나인 Penn Treebank Tokenization
- 규칙 
- 규칙 1. 하이푼(-) 으로 구성된 단어는 하나로 유지한다.
- 규칙 2. doesn't와 같이 아포스트로피로 '접어'가 함께하는 단어는 분리해준다.

In [50]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print(tokenizer.tokenize(text))

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


### 문장 토큰화 (Sentence Tokenization) 
- 문장 분류 (Sentence Segmentation) 
- 

In [51]:
from nltk.tokenize import sent_tokenize
text = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print(sent_tokenize(text))

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


- 마침표가 문장 중간에 여러번 등장하는 경우
- NLTK는 단순히 마침표를 구분자로 하여 문장을 구분하지 않았기 때문에, Ph.D.를 문장 내의 단어로 인식하여 성공적으로 인식하는 것을 볼 수 있습니다.

In [52]:
text = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text))

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


### 한국어 문장 토큰화 패키지 kss

In [53]:
pip install kss

     |████████████████████████████████| 42.4 MB 1.7 MB/s 
     |████████████████████████████████| 170 kB 40.8 MB/s 
  Created wheel for kss: filename=kss-3.3.1.1-py3-none-any.whl size=42449239 sha256=1265f1af5a087b1e371569473ab3d5888554278d89345c1c8574d37619f38436
  Stored in directory: /root/.cache/pip/wheels/6e/9d/1d/52871154eff5273abb86b96f4f984c1cd67c5bde64239b060a
  Created wheel for emoji: filename=emoji-1.6.1-py3-none-any.whl size=169314 sha256=1130de14a9324ebbcec154eca9236e3ed757680937a64dab78b60eea7bc883cc
  Stored in directory: /root/.cache/pip/wheels/ea/5f/d3/03d313ddb3c2a1a427bb4690f1621eea60fe6f2a30cc95940f
Successfully built kss emoji


In [54]:
import kss
text = '딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?'
print(kss.split_sentences(text))

[Korean Sentence Splitter]: Initializing Pynori...


['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.', '이제 해보면 알걸요?']


### 이진분류기(Binary Classifier)
- 문장 토큰화에서의 예외 사항을 발생시키는 마침표의 처리를 위해서 입력에 따라 두 개의 클래스로 분류하는 이진 분류기(binary classifier)를 사용하기도 합니다.
- 1. 마침표(.)가 단어의 일부분일 경우. 즉, 마침표가 약어(abbreivation)로 쓰이는 경우
- 2. 마침표(.)가 정말로 문장의 구분자(boundary)일 경우를 의미할 것입니다.

### 한국어에서의 토큰화의 어려움
- 영어는 New York 와 같은 합성어나 he's 와 같이 줄임말에 대한 예외처리만 한다면,
띄어쓰기(white space) 를 기준으로 하는 띄어쓰기 토큰화를 수행해도 단어 토큰화가 잘 작동한다. 거의 대부분의 경우에서 단어 단위로 띄어쓰기가 이루어지기 때문에 띄어쓰기 토큰화와 단어 토큰화가 거의 같다.

- 하지만 한국어는 영어와는 달리 띄어쓰기만으로는 토큰화를 하기에 부족합니다. 한국어의 경우에는 띄어쓰기 단위가 되는 단위를 '어절'이라고 하는데 즉, 어절 토큰화는 한국어 NLP에서 지양되고 있습니다. 어절 토큰화와 단어 토큰화가 같지 않기 때문입니다. 그 근본적인 이유는 한국어가 영어와는 다른 형태를 가지는 언어인 교착어라는 점에서 기인합니다. 교착어란 조사, 어미 등을 붙여서 말을 만드는 언어를 말합니다.

### 한국어는 교착어다.
- 한국어에는 조사가 존재
- 즉, 띄어쓰기 단위가 영어처럼 독립적인 단어라면 띄어쓰기 단위로 토큰화를 하면 되겠지만 한국어는 어절이 독립적인 단어로 구성되는 것이 아니라 조사 등의 무언가가 붙어있는 경우가 많아서 이를 전부 분리해줘야 한다는 의미입니다.
- 형태소(morpheme)
- 형태소(morpheme)란 뜻을 가진 가장 작은 말의 단위를 말합니다.
- 자립 형태소 : 접사, 어미, 조사와 상관없이 자립하여 사용할 수 있는 형태소. 그 자체로 단어가 된다. 체언(명사, 대명사, 수사), 수식언(관형사, 부사), 감탄사 등이 있다.
- 의존 형태소 : 다른 형태소와 결합하여 사용되는 형태소. 접사, 어미, 조사, 어간를 말한다.

### 한국어는 띄어쓰기가 잘 지켜지지 않는다. 
-  한국어의 경우 띄어쓰기가 지켜지지 않아도 글을 쉽게 이해할 수 있는 언어라는 점
- 한국어는 수많은 코퍼스에서 띄어쓰기가 무시되는 경우가 많아 자연어 처리가 어려워졌다는 것입니다.

### 품사 태깅(part-of-speech tagging)
- 품사에 따라서 단어의 의미가 달라지기도 한다. 
- fly : 동사 (날다) , 명사 (파리) 
- 못 : 명사 와 부사로써의 의미가 다르다 
- 단어 토큰화 과정에서 각 단어가 어떤 품사로 쓰였는지를 구분해놓기도 하는데, 이 작업을 품사 태깅(part-of-speech tagging)이라고 합니다. 

In [55]:
from nltk.tokenize import word_tokenize
text = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
print(word_tokenize(text))

['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']


- PRP는 인칭 대명사
- VBP는 동사
- RB는 부사
- VBG는 현재부사
- IN은 전치사
- NNP는 고유 명사
- NNS는 복수형 명사
- CC는 접속사
- DT는 관사

In [57]:
nltk.download('averaged_perceptron_tagger')
from nltk.tag import pos_tag # 품사 태깅
tokenized_sentence = word_tokenize(text) # 단어 토큰화
print(pos_tag(tokenized_sentence)) 

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


- 한국어 자연어 처리를 위해서는 KoNLPy("코엔엘파이"라고 읽습니다)라는 파이썬 패키지를 사용할 수 있습니다. 코엔엘파이를 통해서 사용할 수 있는 형태소 분석기로 Okt(Open Korea Text), 메캅(Mecab), 코모란(Komoran), 한나눔(Hannanum), 꼬꼬마(Kkma)가 있습니다.
- 한국어 NLP에서 형태소 분석기를 사용한다는 것은 단어 토큰화가 아니라 정확히는 형태소(morpheme) 단위로 형태소 토큰화(morpheme tokenization)를 수행하게 됨을 뜻합니다. 

In [58]:
# 형태소 토큰화
from konlpy.tag import Okt  
okt = Okt()  
print(okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']


In [59]:
# 품사 태깅
print(okt.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

[('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]


In [60]:
# 명사 추출
print(okt.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['코딩', '당신', '연휴', '여행']


- 형태소 추출과 품사 태깅 메소드의 결과를 보면, 조사를 기본적으로 분리하고 있음을 확인할 수 있습니다. 그렇기 때문에 한국어 NLP에서 전처리에 형태소 분석기를 사용하는 것은 꽤 유용합니다.

In [61]:
from konlpy.tag import Kkma  
kkma = Kkma()  
print(kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']


In [63]:
print(kkma.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))  

[('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]


In [62]:
print(kkma.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))  

['코딩', '당신', '연휴', '여행']


# 정제(Cleansing) 와 정규화(Normalization) 
- 코퍼스에서 용도에 맞게 토큰을 분류하는 작업을 토큰화(tokenization)라고 하며, 토큰화 작업 전, 후에는 텍스트 데이터를 용도에 맞게 정제(cleaning) 및 정규화(normalization)하는 일이 항상 함께합니다.

- 정제(cleaning) : 갖고 있는 코퍼스로부터 노이즈 데이터를 제거한다.
- 정규화(normalization) : 표현 방법이 다른 단어들을 통합시켜서 같은 단어로 만들어준다.

- 정제 작업은 토큰화 작업에 방해가 되는 부분들을 배제시키고 토큰화 작업을 수행하기 위해서 토큰화 작업보다 앞서 이루어지기도 하지만, 토큰화 작업 이후에도 여전히 남아있는 노이즈들을 제거하기위해 지속적으로 이루어지기도 합니다. 사실 완벽한 정제 작업은 어려운 편이라서, 대부분의 경우 이 정도면 됐다.라는 일종의 합의점을 찾기도 합니다.

- 1. 규칙에 기반한 표기가 다른 단어들의 통합
- 2. 대, 소문자 통합
- 3. 불필요한 단어의 제거(Removing Unnecessary Words)
    - (1) 등장 빈도가 적은 단어(Removing Rare words)
    - (2) 길이가 짧은 단어(Removing words with a very short length)
- 4. 정규 표현식(Regular Expression)
